//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IShirtService")]
    public interface IShirtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShirtService/GetData", ReplyAction="http://tempuri.org/IShirtService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShirtService/GetData", ReplyAction="http://tempuri.org/IShirtService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShirtService/ShirtPrices", ReplyAction="http://tempuri.org/IShirtService/ShirtPricesResponse")]
        decimal ShirtPrices(string size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShirtService/ShirtPrices", ReplyAction="http://tempuri.org/IShirtService/ShirtPricesResponse")]
        System.Threading.Tasks.Task<decimal> ShirtPricesAsync(string size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShirtServiceChannel : MainForm.ServiceReference1.IShirtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShirtServiceClient : System.ServiceModel.ClientBase<MainForm.ServiceReference1.IShirtService>, MainForm.ServiceReference1.IShirtService {
        
        public ShirtServiceClient() {
        }
        
        public ShirtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShirtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShirtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShirtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public decimal ShirtPrices(string size) {
            return base.Channel.ShirtPrices(size);
        }
        
        public System.Threading.Tasks.Task<decimal> ShirtPricesAsync(string size) {
            return base.Channel.ShirtPricesAsync(size);
        }
    }
}
